# Generated by Django 5.2.11 on 2026-02-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='fee_due_day',
            field=models.IntegerField(default=5, help_text='Day of month when fees become due'),
        ),
    ]
