# Generated by Django 5.2.11 on 2026-02-19 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('standard', models.CharField(help_text='Class / Grade', max_length=50)),
                ('parent_name', models.CharField(max_length=200)),
                ('parent_phone', models.CharField(max_length=20)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('join_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.branch')),
            ],
        ),
    ]
