# Generated by Django 5.2.11 on 2026-02-19 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('student_added', 'Student Added'), ('student_updated', 'Student Updated'), ('student_deleted', 'Student Deleted'), ('fee_paid', 'Fee Paid'), ('fee_due', 'Fee Marked Due'), ('notification_sent', 'Notification Sent'), ('login', 'Login'), ('logout', 'Logout')], max_length=30)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='accounts.branch')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='students.student')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
